# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20160811_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_informs',
            new_name='total_inform',
        ),
    ]
