# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20160811_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='total_bronze',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_gold',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_inform',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_players',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_silver',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_special',
        ),
    ]
