# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_auto_20160724_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
