# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0003_nation_average_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nation',
            options={'ordering': ['-total_players', '-average_rating', 'name'], 'verbose_name': 'Nation', 'verbose_name_plural': 'Nations'},
        ),
    ]
