# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20160811_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-total_players', '-average_rating', 'name'], 'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AddField(
            model_name='league',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
